DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 22
  TEST:
    BATCH_SIZE: 100
  NUM_WORKERS: 4

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["normalize","gaussian_blur","random_flip","random_resized_crop"] #,"gaussian_noise",,"cutout","randomgrayscale""colorjitter"

OPTIM:
  NAME: "adamw"
  LR: 0.0025
  MAX_EPOCH: 30
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5
#  WEIGHT_DECAY: 1e-3

TRAIN:
  PRINT_FREQ: 20

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"

TRAINER:
  MAPLE:
    N_CTX: 0
    CTX_INIT: "a photo of a"
#    CTX_INIT: "X X X X"
    PREC: "fp16"
    PROMPT_DEPTH: 9